### ISSUE TITLE
SETENV/NOSETENV option

### ISSUE THREAD

**Issue by mkg20001** [trifectatechfoundation/sudo-rs#760]
**Describe the feature you'd like see implemented in `sudo-rs`**
The SETENV/NOSETENV option currently is missing

**What problem can be solved with this feature?**
Currently the nixos sudo configuration uses setenv in some places, which we conditionally don't add when using sudo-rs

https://github.com/NixOS/nixpkgs/pull/253876/files#diff-5c91de272e9391a78a1d22be54a571b5dd3585be6e5968f0f62a7c9a790066b1R43

Having this feature would allow feature parity with regular sudo configurations on nixos

**Describe alternatives you've considered**
Currently we disable adding SETENV/NOSETENV when sudo-rs is in use

**Additional context**

**Comment by mkg20001** [comment]
// cc @nbraud

**Comment by squell** [comment]
Thanks for requesting. 

- "user-specific" Defaults was something we delayed until a later milestone (to see if there is a need for it; there are some corner-cases where we wanted to understand it's actual usage better  before just blindly implementing it). I think the example you give for a more flexible `env_keep` is a compelling use case for it. (CC #61)

- one question that would be useful for us as well: it's clear the you want SETENV since NixOS uses it, but *why* does NixOS use the SETENV flag in original sudo? I.e. what problems are solved by allowing a user to use `sudo --preserve-env`?

Back in may, we decided postponed this feature because we were taking a stricter stance on `env_reset` (i.e. not allowing it to be disabled) out of a desire to build a simpler sudo; it would be useful to know what things this prohibits.

**Comment by pvdrz** [comment]
I like the approach of "letting users tell us what they actually need"

**Comment by squell** [comment]
One easy step to take is of course to implement SETENV as a "dummy" tag (i.e. we accept it, but still `-E`/`--preserve-env` is unimplemented).

**Comment by mkg20001** [comment]
It's a good idea, but it will lead to confusing problems later. When something that explicitly depends on SETENV starts failing after switching to sudo-rs very more confusing to debug vs sudo-rs straight out rejecting the option.

Maybe a add dummy and then give a specific error message about the missing SETENV feature would be an idea?

**Comment by squell** [comment]
Yes, we should emit a diagnostic for it and not just silently break things. We should probably do that for the other not-supported tags too (for our reference: cc #546 and #700).

**Comment by yorickvP** [comment]
I believe the reason NixOS uses SETENV is that it installs a lot of packages in the user environment that the user may want to run as root. An unsuccessful attempt to remove it was made a few years ago. There might be a better way to do this nowadays.

**Comment by MayRedwood** [comment]
If I may step in, I find that `--preserve-env` is very useful when I need to run graphical apps as root
This is, admittedly, not very common, but it's one of the few ways I've found to get `gparted` to run in a WM environment

**Comment by squell** [comment]
Two questions:

* If `--preserve-env` is used, is this typically in the "who cares, here's my entire environment" way, or in the `--preserve-env=VAR1,VAR2,VAR3` way? (This second approach sounds much more secure to me)

* And if the answer is "the second way", what's the perceived benefit between:

> `sudo --preserve-env=VAR`

vs

> `sudo VAR="$VAR"`

Note that `SETENV` support is also needed to allow the second version; I've already added that support locally but am having some doubt about whether supporting the use case of `-E` is such a great idea: it is essentially the same as having `Defaults !env_reset` and means we have to add support for `env_delete` as well. In general we think the 'whitelisting some environment vars' is vastly preferable to 'blacklisting certain environment vars'.
