### ISSUE TITLE
Remove `actions-rs` from CI

### ISSUE THREAD

**Issue by squell** [trifectatechfoundation/sudo-rs#852]
Our CI uses `actions-rs`. I think those can be replaced by simple `run: ` invocations; especially seeing that `actions-rs` is no longer maintained.

There's also some other third-party actions being used where I wonder if we really need them:
- [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache)
- [awalsh128/cache-apt-pkgs-action](https://github.com/awalsh128/cache-apt-pkgs-action); i think we introduced that one since a naked `apt-get` was sometimes not working.
- [taiki-e/install-action](https://github.com/taiki-e/install-action); can't we just use `cargo install` there?

**Comment by rnijveld** [comment]
We should remove actions-rs, given its been unmaintained for several years now already. The rust-cache action makes caching Rust code compilation way easier, I would keep that. The apt one caches installation of apt packages, that speeds it up a whole bunch. And the install-action uses precompiled binaries, so that also saves a lot of time.
